VERSION = 'e1'

COLOR_PLAN = '#126DEF'
COLOR_ACT = '#126DEF'
COLOR_LOSS = '#9E0002'
COLOR_WIN =  '#0F7003'
COLOR_HIGHLIGHT = '#FFC910'
COLOR_NEUTRAL = '#D7D7D7'

KEY_CONTINUE = ' '
KEY_SWITCH = 'f'
KEY_SELECT = 'j'
KEY_ABORT = 'a'

LABEL_CONTINUE = 'Space'
LABEL_SELECT = 'Key J'
LABEL_SWITCH = 'Key F'


